### ISSUE TITLE
Fehler beim gradle import in eclipse

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MServer#20]
```
Synchronize Gradle builds with workspace failed due to an unexpected error.
Cannot nest 'MServer/src/main/java' inside 'MServer/src'. To enable the nesting exclude 'main/' from 'MServer/src'
Java Model Exception: Java Model Status [Cannot nest 'MServer/src/main/java' inside 'MServer/src'. To enable the nesting exclude 'main/' from 'MServer/src']
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:786)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3097)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3059)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3112)
	at org.eclipse.buildship.core.workspace.internal.SourceFolderUpdater.updateClasspath(SourceFolderUpdater.java:234)
	at org.eclipse.buildship.core.workspace.internal.SourceFolderUpdater.updateClasspath(SourceFolderUpdater.java:82)
	at org.eclipse.buildship.core.workspace.internal.SourceFolderUpdater.update(SourceFolderUpdater.java:261)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeOpenJavaProject(SynchronizeGradleBuildOperation.java:223)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeOpenWorkspaceProject(SynchronizeGradleBuildOperation.java:213)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.addExistingEclipseProjectToWorkspace(SynchronizeGradleBuildOperation.java:258)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeNonWorkspaceProject(SynchronizeGradleBuildOperation.java:245)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleProjectWithWorkspaceProject(SynchronizeGradleBuildOperation.java:179)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleBuildWithWorkspace(SynchronizeGradleBuildOperation.java:141)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.access$000(SynchronizeGradleBuildOperation.java:106)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$1.run(SynchronizeGradleBuildOperation.java:123)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:39)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5521)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5478)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:120)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:79)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:69)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:63)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by kaklakariada** [comment]
Wie kann ich den Fehler reproduzieren? Der Import funktioniert bei mir, wenn alle drei Projekte im gleichen Verzeichnis liegen.
Du könntest versuchen, die Dateien `.project` und `.classpath` aus den Projektverzeichnissen zu löschen und die Projekte nochmal importieren.

**Comment by alex1702** [comment]
ich probiers nochmal

**Comment by alex1702** [comment]
ok am laptop 2 hab ich es jetzt auch ohne probleme hinbekommen.
