### ISSUE TITLE
ZDF: keine neuen Einträge

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#255]
Im [Forum](https://forum.mediathekview.de/topic/785/zdf-20171007-055700-filmliste-nicht-aktuell) wurde gemeldet, dass für das ZDF keine neuen Einträge mehr erscheinen.

Ergebnis meiner Analyse: der Bearer für die Authentifizierung wird nicht mehr in configuration.json übermittelt und der als Fallback hinterlegte Defaultwert ist nicht mehr gültig.

- [x] Schnelle Lösung für Lauffähigkeit des Crawlers durch Aktualisierung des Defaultwertes
- [x] neue Lösung zur Ermittlung des Bearers zur Laufzeit

**Comment by Nicklas2751** [comment]
Ah der andere Token hat sich auch geändert. Der Token für die Suche wurde von `f4ba81fa117681c42383194a7103251db2981962` auf `309fa9bc88933de7256f4f6f6c5d3373cc36517c`geändert. Ausgelesen werden kann er im Quelltext der Startseite als: `apiToken` in einem der Script bereiche.

**Comment by pidoubleyou** [comment]
Danke für die Recherche. Habe die Tokenermittlung umgebaut auf das Parsen der Startseite.
Wenn etwas schief geht, werden die neuen Defaulttokens verwendet.

**Comment by alex1702** [comment]
Branch scheint Fehlerhaft zu sein.

**Comment by alex1702** [comment]
Beim starten:
```
java.lang.NoClassDefFoundError: com/jidesoft/utils/SystemInfo
        at de.mediathekview.mlib.tool.Log.versionMsg(Log.java:81)
        at mServer.crawler.CrawlerTool.startMsg(CrawlerTool.java:35)
        at mServer.crawler.Crawler.run(Crawler.java:52)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.jidesoft.utils.SystemInfo
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 4 more
```

**Comment by alex1702** [comment]
Ok ich glaub ich hab den Fehler gefunden.
