### ISSUE TITLE
X11 Fehler beim starten

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MServer#3]
Folgender Fehler:
`X11 connection rejected because of wrong authentication.
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1734)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1266)
	at mServer.Main.main(Main.java:38)`
Umstieg auf normale Threads

**Comment by Nicklas2751** [comment]
Hmm looks like Xaver uses a AWT class to run the code in a new thread.

**Comment by derreisende77** [comment]
It´s a mixup between AWT/Swing code (which was used before) and JavaFX.
EventQueue.invokeLater is clearly wrong here and might be replaced by Platform.runLater to put everything on JavaFX thread. But looking at the code I see no reason by just removing the whole invokeLater() call and just calling Application.launch and the rest...

**Comment by alex1702** [comment]
Später sollte diese X-Server abhängigkeit aus dem MServer rausfliegen.
Als Workaround gilt im moment eine Video virtualisierung zu aktivieren, falls man den Server in einer KVM oder anderen Virtualisierunglösung laufen lässt.

**Comment by alex1702** [comment]
geschlossen mit commit [46f588d](https://github.com/mediathekview/MServer/commit/46f588dfb3c2de2a67cc120bc0c4a190cb3befe1)
