### ISSUE TITLE
Fertigstellung NDR-Crawler für neue Architektur

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#335]
Der NDR-Crawler ist zwar in der neuen Architektur verfügbar, folgendes ist aber noch zu tun:

- [x] Untertitel auslesen (dabei #333 berücksichtigen)
- [x] Qualität "auto" so berücksichtigen, dass nicht das Debug-Log voll geschrieben wird: 
`19:25:18.682 2018-01-17 19:25:18,682 [ForkJoinPool-1-worker-9] DEBUG: Can't convert quality %s to an integer.
java.lang.NumberFormatException: For input string: "auto"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at de.mediathekview.mserver.crawler.ard.json.ArdMediaArrayToDownloadUrlsConverter.toDownloadUrls(ArdMediaArrayToDownloadUrlsConverter.java:58)
	at de.mediathekview.mserver.crawler.ndr.parser.NdrFilmDeserializer.deserialize(NdrFilmDeserializer.java:56)`
- [x] Prüfung Logik zur Ermittlung des Datums: Debug-Log enthält viele Einträge, dass Datum nicht geparsed werden kann:
`DEBUG: The NDR date time "Sportclub" can't be parsed. Using actual date time.
java.time.format.DateTimeParseException: Text 'Sportclub' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at de.mediathekview.mserver.crawler.ndr.tasks.NdrSendungsfolgedetailsTask.parseTime(NdrSendungsfolgedetailsTask.java:66)
	at de.mediathekview.mserver.crawler.ndr.tasks.NdrSendungsfolgedetailsTask.processDocument(NdrSendungsfolgedetailsTask.java:92)`
- [x] fehlende Sendungen wie z.B. Tatort aufnehmen. Eventuell hängt das mit den Debug-Ausgaben bzgl. fehlenden Titel zusammen. Eventuell hilft dabei #329:
`DEBUG: An error occurred during NDR editing due to a missing element "title".`
- [x] viele Seiten beinhalten laut Log keine Videos. Prüfung, ob Deserializer fehlerhaft ist. Wenn die Seiten tatsächlich keine Videos beinhalten, prüfen, ob diese bereits beim Parsen der Übersichtsseiten entfernt werden können. Wenn nicht, sollte zumindest kein Log erscheinen!

**Comment by pidoubleyou** [comment]
Meldungen bzgl. Qualität "auto" in Debug-Log mit #349 bereinigt

**Comment by pidoubleyou** [comment]
die vielen Seiten ohne Video lassen sich leider nicht anders behandeln, bleibt so.

**Comment by pidoubleyou** [comment]
Offene Punkte/Bugs:

- [ ] unzählige Fehlermeldungen in Log "no film found for url", Seiten enthalten auch keine Videos, somit sollte da auch keine Errors im Log erscheinen

- [ ] Filme doppelt in Filmliste unter zwei verschiedenen Themen/Titeln (war in alten Crawler auch schon so, aber vielleicht geht es besser). Beispiele:
- Thema: diverse 7 Tage...-Sendungen, z.B. 7 Tage... im Kinderhospiz
- Thema: diverse die nordstory-Sendungen, z.B. Die Küstenschützer
- Thema: Büttenwarder op Platt: Im Dutt vom 16.9.
- Titel: Ameland... mit Judith Rakers / Ameland ... mit Judith Rakers
- Titel: Auf der Ems durch Ostfriesland / Auf der Ems durch Ostfriesland - Von Papenburg bis zum Dollart
- Titel und Thema: BINGO!-Sendung vom 16.9.

**Comment by pidoubleyou** [comment]
Log-Level reduziert, ganz herausnehmen ist nicht sinnvoll, sonst wundert man sich, warum die Fehlerstatistik so hoch ist aber keine Meldungen vorhanden sind.

Filme doppelt lässt sich nicht verhindern, beide verweisen auf unterschiedlich aufgebaute Seiten. Ist beim NDR leider so.
