### ISSUE TITLE
Sender-spezifische Konfiguration verwendet Defaultwerte

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#470]
Wenn für einen Sender eine senderspezifische Konfiguration hinterlegt ist, dann werden in `crawlerConfig` nur die senderspezifischen gesetzten Felder aus der Konfiguration berücksichtigt, für die übrigen Felder gelten die Defaultwerte.

Dies führt dazu, dass globalen Einstellungen z.B. für die Suchtiefe nicht berücksichtigt werden, wenn wie bei KIKA nur das SocketTimeout gesetzt wird. 

Anmerkung: wenn eine senderspezifische Konfiguration hinterlegt ist, dann ist `crawlerConfig` vom Typ `MServerBasicConfigDTO` sonst vom Typ `MServerConfigDTO`

**Comment by pidoubleyou** [comment]
Offensichtlich gibt es hier doch noch ein Problem:
beim Start eines Crawlers mit senderspezifischer Konfig tritt momentan folgende Exception auf:

```
java.lang.NullPointerException
	at de.mediathekview.mserver.crawler.basic.AbstractCrawler.call(AbstractCrawler.java:62)
	at de.mediathekview.mserver.crawler.basic.AbstractCrawler.call(AbstractCrawler.java:25)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by codingPF** [comment]
@pidoubleyou  bei meinen Beispielen hat das mittlerweile geklappt...kannst du das nöchmal prüfen und zu machen?

**Comment by pidoubleyou** [comment]
stimmt, hat sich anscheinend anderweitig gelöst.
