### ISSUE TITLE
PHOENIX: Suchlauf endet manchmal nicht

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#481]
Der PHOENIX-Crawler beendet sich manchmal nicht korrekt.

Ursache ist folgende Exception:
`
java.lang.NullPointerException
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2614)
	at mServer.crawler.sender.phoenix.PhoenixCrawler.addToList(PhoenixCrawler.java:45)
	at mServer.crawler.sender.MediathekReader.run(MediathekReader.java:194)
	at java.lang.Thread.run(Thread.java:748)

* Fehlernr: 397543600
* Exception: null
* Fehler(MSearch): MediathekReader.run
*           PHOENIX
`

**Comment by pidoubleyou** [comment]
Ursache: In der API von PHOENIX funktioniert das Paging manchmal nicht korrekt, kann man auch auf der Webseite nachvollziehen.

Es wird immer die gleiche URL als nächste Seite geliefert, so dass irgendwann ein StackOverflow erfolgt.

Workaround eingebaut, muss auf jeden Fall noch in Develop verifiziert werden, ob der neue Crawler auch das gleiche Problem besitzt.
