### ISSUE TITLE
SRF: NullPointerException in Logfile

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#549]
In den aktuellen Suchläufen sind diverse NullPointerException für den SRF enthalten:
`java.lang.NullPointerException
	at mServer.crawler.sender.srf.parser.SrfFilmJsonDeserializer.deserialize(SrfFilmJsonDeserializer.java:66)
	at mServer.crawler.sender.srf.parser.SrfFilmJsonDeserializer.deserialize(SrfFilmJsonDeserializer.java:32)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at mServer.crawler.sender.srf.tasks.SrfFilmDetailTask.parseFilm(SrfFilmDetailTask.java:63)
	at mServer.crawler.sender.srf.tasks.SrfFilmDetailTask.processRestTarget(SrfFilmDetailTask.java:39)
	at mServer.crawler.sender.base.AbstractRestTask.processElement(AbstractRestTask.java:69)
	at mServer.crawler.sender.base.AbstractRestTask.processElement(AbstractRestTask.java:25)
	at mServer.crawler.sender.base.AbstractRecursivConverterTask.processElements(AbstractRecursivConverterTask.java:58)
	at mServer.crawler.sender.base.AbstractRecursivConverterTask.compute(AbstractRecursivConverterTask.java:65)
	at mServer.crawler.sender.base.AbstractRecursivConverterTask.compute(AbstractRecursivConverterTask.java:71)
	at mServer.crawler.sender.base.AbstractRecursivConverterTask.compute(AbstractRecursivConverterTask.java:23)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by pidoubleyou** [comment]
Ursache: VideoUrls wegen Geo-Blocking nicht in JSON verfügbar
