### ISSUE TITLE
Unsupported major.minor version 52.0 (java.lang.UnsupportedClassVersionError: mServer/Main)

### ISSUE THREAD

**Issue by leveled-up** [mediathekview/MServer#70]
Wenn ich das Release 2.5.2 als TAR herunterladen, entpacke und ./STARTEN__MServer.sh ausführe, erhalte ich dies. Ich verwende **Debian 8** (Lite, also keine GUI) und die Packages **default-jre** und **default-jdk** sind installiert.

`root@debian-1:~/mserver$ ./STARTEN__MServer.sh
%% und Tschuess
%% -----------------------------------------
root@debian-1:~/mserver$ Exception in thread "main" java.lang.UnsupportedClassVersionError: mServer/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
^C`

Was muss ich an meiner Installation verändern, damit es funktioniert?

Danke.

**Comment by alex1702** [comment]
Was ergibt `java -java -version` ?

**Comment by Nicklas2751** [comment]
Du brauchst mindestens OpenJRE 8 und dann noch OpenJFX.

**Comment by leveled-up** [comment]
Das Folgende:

`Unrecognized option: -java
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

**Comment by Nicklas2751** [comment]
Alex meinte "java -version" im Terminal

**Comment by leveled-up** [comment]
Dann:
`java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-2~deb8u1)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)`

**Comment by alex1702** [comment]
Jap die Version wird nicht unterstützt. Wie Nicklas schon sagte brauchst du mindestens 1.8 bzw. Java8. müsste eventuell mit `sudo apt-get install openjdk-8-jre` klappen.

**Comment by leveled-up** [comment]
```
root@debian-1:~/mserver$ apt-get install openjdk-8-jre
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libice-dev libpthread-stubs0-dev libsm-dev libx11-dev libx11-doc libxau-dev libxcb1-dev libxdmcp-dev
  libxt-dev libxt6 openjdk-7-jdk openjdk-7-jre x11proto-core-dev x11proto-input-dev x11proto-kb-dev
  xorg-sgml-doctools xtrans-dev
Use 'apt-get autoremove' to remove them.
Suggested packages:
  icedtea-8-plugin
The following NEW packages will be installed:
  openjdk-8-jre
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/69.9 kB of archives.
After this operation, 359 kB of additional disk space will be used.
Selecting previously unselected package openjdk-8-jre:amd64.
(Reading database ... 34764 files and directories currently installed.)
Preparing to unpack .../openjdk-8-jre_8u111-b14-2~bpo8+1_amd64.deb ...
Unpacking openjdk-8-jre:amd64 (8u111-b14-2~bpo8+1) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for mime-support (3.58) ...
Setting up openjdk-8-jre:amd64 (8u111-b14-2~bpo8+1) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
root@debian-1:~/mserver$ ./STARTEN__MServer.sh 
%% und Tschuess
%% -----------------------------------------
root@debian-1:~/mserver$ Exception in thread "main" java.lang.UnsupportedClassVersionError: mServer/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

root@debian-1:~/mserver$ 
```

**Comment by alex1702** [comment]
Der hat die noch nicht als default jre gesetzt.
Nutze dazu: `sudo update-alternatives --config java` und wähle da Java8 aus

**Comment by leveled-up** [comment]
Ah, danke. Jetzt kommt der Fehler nicht mehr. :+1:
