### ISSUE TITLE
ARTE: Film wird bei unvollständigen Untertitel-Infos nicht aufgenommen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#722]
Im [Forum](https://forum.mediathekview.de/topic/4193/arte-de-salamander-folge-05-betrug/2) wurde gemeldet, dass eine Episode einer Serie in der Liste fehlt.

Ergebnis der Analyse:
für Filme mit Untertitel wird nur die HD-Url gefunden. Dies führt zu einer NullPointerException:
`java.lang.NullPointerException
	at mServer.crawler.CrawlerTool.getKlein(CrawlerTool.java:127)
	at mServer.crawler.CrawlerTool.addUrlHd(CrawlerTool.java:110)
	at mServer.crawler.sender.arte.ArteProgramIdToDatenFilmCallable.createFilm(ArteProgramIdToDatenFilmCallable.java:99)
	at mServer.crawler.sender.arte.ArteProgramIdToDatenFilmCallable.call(ArteProgramIdToDatenFilmCallable.java:71)
	at mServer.crawler.sender.arte.ArteJsonObjectToDatenFilmCallable.call(ArteJsonObjectToDatenFilmCallable.java:36)
	at mServer.crawler.sender.arte.ArteDatenFilmDeserializer.deserialize(ArteDatenFilmDeserializer.java:37)
	at mServer.crawler.sender.arte.ArteDatenFilmDeserializer.deserialize(ArteDatenFilmDeserializer.java:19)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at mServer.crawler.sender.arte.ArteHttpClient.executeRequest(ArteHttpClient.java:73)
	at mServer.crawler.sender.arte.MediathekArte_de$ThemaLaden.addFilmeForTag(MediathekArte_de.java:179)
	at mServer.crawler.sender.arte.MediathekArte_de$ThemaLaden.run(MediathekArte_de.java:169)`

* [x] Exception-Handling bei ARTE prüfen, denn diese erscheinen nicht im Crawler-Log 
* [x] bei Exceptions von Untertitel/Audiodeskription zumindest den Standard-Film aufnehmen
* [x] prüfen, ob Film auch ohne normaler Video-Url aufgenommen werden kann
* [x] prüfen, ob auch Develop betroffen ist

**Comment by pidoubleyou** [comment]
develop ist nicht betroffen.
