### ISSUE TITLE
UnknownHostException beim durchlauf 

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MServer#8]
```
java.net.UnknownHostException: www.kika.dehttps
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at mSearch.filmeSuchen.GetUrl.getUri(GetUrl.java:148)
        at mSearch.filmeSuchen.GetUrl.getUri(GetUrl.java:82)
        at mSearch.filmeSuchen.sender.MediathekKika$ThemaLaden.ladenSerien_2(MediathekKika.java:234)
        at mSearch.filmeSuchen.sender.MediathekKika$ThemaLaden.ladenSerien_1(MediathekKika.java:209)
        at mSearch.filmeSuchen.sender.MediathekKika$ThemaLaden.run(MediathekKika.java:142)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: www.kika.dehttps
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2943)
        at java.net.URLConnection.getContentEncoding(URLConnection.java:523)
        at mSearch.filmeSuchen.GetUrl.getUri(GetUrl.java:147)
        ... 5 more

* Fehlernr: 379861049
* Exception: www.kika.dehttps
* Fehler(MSearch): GetUrl.getUri
*
*           Sender: KiKA - timout: 10000 Versuche: 1
*           URL: http://www.kika.dehttps://www.mein-kika.de/gruppe/4/forum/122.html
*           Themenseite

  [ #######--- ]  88249 Seiten / 77% von 4802 Themen / Filme: 44946 / Dauer[Min]: 79 / R-Sender: 3
```
Diesen Fehler hab ich grad zufällig in den Logs ausgeschnappt beim max durchlauf.

**Comment by xaverW** [comment]
www.kika.dehttps

da wird vom crawler (gehört auch zu msearch) eine falsche URL gefunden, das kann viele Ursachen haben: eine Seite anders aufgebaut, ist keine Filmseite, ...
Das kommt öfters vor, solange keine Filme fehlen, kann man das lassen.
